version: "3"

services:
  db:
    environment:
      POSTGRES_DB: talkshop
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    networks:
      webnet:
        aliases:
          - postgres
  redis:
    image: redis
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: redis
    networks:
      webnet:
  web:
    environment:
      DB_HOST: postgres  # Use the alias as the DB_HOST
      REDIS_HOST: redis
    image: talkshop-server
    networks:
      webnet:
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp

networks:
  webnet:
    name: bullmq-testing_webnet
